services:
  base:
    hostname: livoscan
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        ROS_DISTRO: humble
        USERNAME: user
        USER_UID: 1000
    network_mode: host
    ipc: host
    pid: host
    stdin_open: true
    tty: true

    working_dir: /home/user/workspace
    user: user
    volumes:
      - .:/home/user/workspace
