name: livoscan

services:
  base:
    container_name: livoscan-container
    hostname: livoscan
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USERNAME: ${USER:-user}
    network_mode: host
    ipc: host
    pid: host
    stdin_open: true
    tty: true
    working_dir: /home/${USER:-user}
    user: ${USER:-user}

    volumes:
      - .:/home/${USER:-user}

  dev:
    extends: base
