name: livoscan

services:
  dev:
    extends:
      file: compose-base.yaml
      service: base
    container_name: livoscan-dev

  prod:
    extends:
      file: compose-base.yaml
      service: base
    container_name: livoscan-prod

    command:
      - ./colcon_build.sh
      - bash
