services:
  base:
    hostname: livoscan
    extra_hosts:
      - "livoscan:127.0.0.1"
    platform: linux/arm64
    runtime: nvidia
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        ROS_DISTRO: humble
        # USERNAME: root
        # USER_UID: 1000
    privileged: true
    network_mode: host
    ipc: host
    pid: host
    stdin_open: true
    tty: true

    entrypoint: ["./entrypoint.sh"]    

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all,compute,video,graphics,utility
      - DISPLAY=${RVIZ_DISPLAY:-:0}
      - XDG_RUNTIME_DIR=/tmp/runtime-user
      # OpenGL use GPU
      - __NV_PRIME_RENDER_OFFLOAD=1
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
      # Vulkan use GPU
      - __VK_LAYER_NV_optimus=NVIDIA_only
    # devices:
      # - /dev/dri:/dev/dri
      # - /dev/v4l/by-id/usb-Technologies__Inc._ZED_2i_OV0001-video-index0:/dev/video0
      # - /dev/v4l/by-id/usb-Technologies__Inc._ZED_2i_OV0001-video-index1:/dev/video1
      - CYCLONEDDS_URI=file:///root/workspace/cyclonedds.xml
    # group_add:
    #   - video
    #   - "983"
    working_dir: /root/workspace
    user: root
    volumes:
      - .:/root/workspace:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
